// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoYukKrLiZP9nht3tUMh2wqmSUvP6Inn8',
    appId: '1:231131893492:web:73ced0d9d1c330a24258a1',
    messagingSenderId: '231131893492',
    projectId: 'workoutml',
    authDomain: 'workoutml.firebaseapp.com',
    storageBucket: 'workoutml.firebasestorage.app',
    measurementId: 'G-Y6J3FR71L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAUYmSa77TM7bqvRmm3jWs2RCjgsjMGT0',
    appId: '1:231131893492:android:6bd7869351952dbd4258a1',
    messagingSenderId: '231131893492',
    projectId: 'workoutml',
    storageBucket: 'workoutml.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbRC1xpEIoprg2cLAi031t88hw_F4vsQ',
    appId: '1:231131893492:ios:9426995fc1f870ad4258a1',
    messagingSenderId: '231131893492',
    projectId: 'workoutml',
    storageBucket: 'workoutml.firebasestorage.app',
    androidClientId: '231131893492-uf2t8o4rge270ifbavoa5h3rdkto9p19.apps.googleusercontent.com',
    iosClientId: '231131893492-vofde8h5tebekl4318hv17eebcun12sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEbRC1xpEIoprg2cLAi031t88hw_F4vsQ',
    appId: '1:231131893492:ios:9426995fc1f870ad4258a1',
    messagingSenderId: '231131893492',
    projectId: 'workoutml',
    storageBucket: 'workoutml.firebasestorage.app',
    androidClientId: '231131893492-uf2t8o4rge270ifbavoa5h3rdkto9p19.apps.googleusercontent.com',
    iosClientId: '231131893492-vofde8h5tebekl4318hv17eebcun12sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoYukKrLiZP9nht3tUMh2wqmSUvP6Inn8',
    appId: '1:231131893492:web:fef4ddface31c4914258a1',
    messagingSenderId: '231131893492',
    projectId: 'workoutml',
    authDomain: 'workoutml.firebaseapp.com',
    storageBucket: 'workoutml.firebasestorage.app',
    measurementId: 'G-0YM30J50J8',
  );
}
